### DISCUSSION TITLE
Changing usage of git dependencies to include tags

### DISCUSSION THREAD

**Discussion by jake-g00dwin** [ch32-rs/ch32-hal#69] [Ideas]
I've recently ran into issues where I ended up with multiple versions of the `qingke` and `qingke-rt` dependencies being pulled into a project I've been working on.

I think it may be a good idea to use github tags so that including the dependencies can be done by tag to help prevent these kind of issues.

something like:

```toml
# ...SNIP...

ch32-hal = {git = "https://github.com/ch32-rs/ch32-hal",
    tag = "0.2.1",
    features = [
        "ch32v203k8t6",
        "embassy",
        "rt",
        "time-driver-tim2",
    ],
    default-features = false,
}

# ...SNIP...

qingke-rt = "0.2.1"
qingke = "0.2.0"

```

Really I'm just purposing that we could have tags that would be tied to or match the crates.io version numbers.

I know it's possible to use the `rev` key but that seems a bit messy imho.

**Comment by jsprog** [comment]
> I've recently ran into issues where I ended up with multiple versions of the qingke and qingke-rt dependencies being pulled into a project I've been working on.

My dependencies on `qingke` and `qingke-rt` are following the examples by setting the version to *
```toml
qingke = "*"
qingke-rt = { version = "*", features = [] }
```


> I think it may be a good idea to use github tags so that including the dependencies can be done by tag to help prevent these kind of issues.
I know it's possible to use the rev key but that seems a bit messy imho.

Espressif already solved this by moving nearly all packages into a single repository [https://github.com/esp-rs/esp-hal](https://github.com/esp-rs/esp-hal), thus patching different packages with the same `rev` would work.


> Really I'm just purposing that we could have tags that would be tied to or match the crates.io version numbers.

Nothing is released at [https://crates.io/crates/ch32-hal](https://crates.io/crates/ch32-hal)
